title: Tobias Köhne
description: Geophysics PhD Student
remote_theme: hydecorp/hydejack@v9.1.5
plugins:
  - jekyll-include-cache
font: Helvetica, Arial, sans-serif
font_heading: Helvetica, Arial, sans-serif
google_fonts: false
google_analytics: false
author:
  name:  Tobias Köhne
  email: tkoehne@caltech.edu
  social:
    github: tobiscode
    orcid: 0000-0002-8400-7255
    gscholar: 1Un3svkAAAAJ
    caltech: http://www.seismolab.caltech.edu/koehne_t.html
    email: tkoehne@caltech.edu
accent_image: /assets/website-background.jpg
accent_color: rgb(45,82,146)
lang: en
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
menu:
  - title: Research
    url: /research
  - title: CV
    url: /cv
no_page_style: true
no_toc: true
no_breadcrumbs: true
no_large_headings: true
no_search: true
copyright: © Tobias Köhne 2023. All rights reserved.
