theme: jekyll-theme-cayman
title: Tobias Köhne
description: PhD Student
remote_theme: hydecorp/hydejack@v9.1.5
plugins:
  - jekyll-include-cache
google_fonts: false
author:
  name:  Tobias Köhne
  email: tkoehne@caltech.edu
  social:
    github: tobiscode
    orcid: 0000-0002-8400-7255
accent_image: /assets/website-background.jpg
